# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(591, 462)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(490, 180, 81, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(470, 210, 41, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(470, 230, 41, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(470, 250, 41, 16))
        self.label_4.setObjectName("label_4")
        self.file_select = QtWidgets.QPushButton(self.centralWidget)
        self.file_select.setGeometry(QtCore.QRect(470, 30, 111, 28))
        self.file_select.setObjectName("file_select")
        self.generate_graphs = QtWidgets.QPushButton(self.centralWidget)
        self.generate_graphs.setGeometry(QtCore.QRect(470, 150, 111, 28))
        self.generate_graphs.setObjectName("generate_graphs")
        self.file_display = QtWidgets.QLineEdit(self.centralWidget)
        self.file_display.setGeometry(QtCore.QRect(470, 60, 111, 22))
        self.file_display.setObjectName("file_display")
        self.view_previous = QtWidgets.QPushButton(self.centralWidget)
        self.view_previous.setGeometry(QtCore.QRect(10, 370, 91, 28))
        self.view_previous.setObjectName("view_previous")
        self.view_next = QtWidgets.QPushButton(self.centralWidget)
        self.view_next.setGeometry(QtCore.QRect(100, 370, 91, 28))
        self.view_next.setObjectName("view_next")
        self.apply = QtWidgets.QPushButton(self.centralWidget)
        self.apply.setGeometry(QtCore.QRect(190, 370, 91, 28))
        self.apply.setObjectName("apply")
        self.save_2 = QtWidgets.QPushButton(self.centralWidget)
        self.save_2.setGeometry(QtCore.QRect(280, 370, 91, 28))
        self.save_2.setObjectName("save_2")
        self.save_all = QtWidgets.QPushButton(self.centralWidget)
        self.save_all.setGeometry(QtCore.QRect(370, 370, 91, 28))
        self.save_all.setObjectName("save_all")
        self.title = QtWidgets.QLineEdit(self.centralWidget)
        self.title.setGeometry(QtCore.QRect(510, 210, 71, 22))
        self.title.setObjectName("title")
        self.x_axis = QtWidgets.QLineEdit(self.centralWidget)
        self.x_axis.setGeometry(QtCore.QRect(510, 230, 71, 22))
        self.x_axis.setObjectName("x_axis")
        self.y_axis = QtWidgets.QLineEdit(self.centralWidget)
        self.y_axis.setGeometry(QtCore.QRect(510, 250, 71, 22))
        self.y_axis.setObjectName("y_axis")
        self.graph_options = QtWidgets.QPushButton(self.centralWidget)
        self.graph_options.setGeometry(QtCore.QRect(470, 280, 111, 28))
        self.graph_options.setObjectName("graph_options")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_5.setObjectName("label_5")
        self.graph_count = QtWidgets.QLabel(self.centralWidget)
        self.graph_count.setGeometry(QtCore.QRect(100, 10, 21, 16))
        self.graph_count.setObjectName("graph_count")
        self.select_save_loc = QtWidgets.QPushButton(self.centralWidget)
        self.select_save_loc.setGeometry(QtCore.QRect(470, 90, 111, 28))
        self.select_save_loc.setObjectName("select_save_loc")
        self.display_save_loc = QtWidgets.QLineEdit(self.centralWidget)
        self.display_save_loc.setGeometry(QtCore.QRect(470, 120, 111, 22))
        self.display_save_loc.setObjectName("display_save_loc")
        self.save_status = QtWidgets.QLabel(self.centralWidget)
        self.save_status.setGeometry(QtCore.QRect(480, 370, 101, 21))
        self.save_status.setObjectName("save_status")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(10, 400, 41, 21))
        self.label_6.setObjectName("label_6")
        self.program_status = QtWidgets.QLabel(self.centralWidget)
        self.program_status.setGeometry(QtCore.QRect(50, 400, 231, 21))
        self.program_status.setObjectName("program_status")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Graph Options"))
        self.label_2.setText(_translate("MainWindow", "Title:"))
        self.label_3.setText(_translate("MainWindow", "x-Axis:"))
        self.label_4.setText(_translate("MainWindow", "y-Axis:"))
        self.file_select.setText(_translate("MainWindow", "Select File"))
        self.generate_graphs.setText(_translate("MainWindow", "Generate Graphs"))
        self.file_display.setText(_translate("MainWindow", "No file selected"))
        self.view_previous.setText(_translate("MainWindow", "View Previous"))
        self.view_next.setText(_translate("MainWindow", "View Next"))
        self.apply.setText(_translate("MainWindow", "Apply"))
        self.save_2.setText(_translate("MainWindow", "Save"))
        self.save_all.setText(_translate("MainWindow", "Save All"))
        self.graph_options.setText(_translate("MainWindow", "More Graph Options"))
        self.label_5.setText(_translate("MainWindow", "Viewing Graph:"))
        self.graph_count.setText(_translate("MainWindow", "0/0"))
        self.select_save_loc.setText(_translate("MainWindow", "Select Save Location"))
        self.display_save_loc.setText(_translate("MainWindow", "No location selected"))
        self.save_status.setText(_translate("MainWindow", "No unsaved graphs"))
        self.label_6.setText(_translate("MainWindow", "Status:"))
        self.program_status.setText(_translate("MainWindow", "No Datafiles imported"))

