# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(991, 672)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(870, 220, 69, 16))
        self.label.setObjectName("label")
        self.Savefile = QtWidgets.QLabel(self.centralWidget)
        self.Savefile.setGeometry(QtCore.QRect(830, 240, 51, 16))
        self.Savefile.setObjectName("Savefile")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(830, 270, 41, 16))
        self.label_4.setObjectName("label_4")
        self.file_select = QtWidgets.QPushButton(self.centralWidget)
        self.file_select.setGeometry(QtCore.QRect(830, 20, 151, 31))
        self.file_select.setObjectName("file_select")
        self.generate_graphs = QtWidgets.QPushButton(self.centralWidget)
        self.generate_graphs.setGeometry(QtCore.QRect(830, 180, 151, 31))
        self.generate_graphs.setObjectName("generate_graphs")
        self.file_display = QtWidgets.QLineEdit(self.centralWidget)
        self.file_display.setGeometry(QtCore.QRect(830, 60, 151, 20))
        self.file_display.setObjectName("file_display")
        self.view_previous = QtWidgets.QPushButton(self.centralWidget)
        self.view_previous.setGeometry(QtCore.QRect(830, 490, 81, 31))
        self.view_previous.setObjectName("view_previous")
        self.view_next = QtWidgets.QPushButton(self.centralWidget)
        self.view_next.setGeometry(QtCore.QRect(910, 490, 71, 31))
        self.view_next.setObjectName("view_next")
        self.save = QtWidgets.QPushButton(self.centralWidget)
        self.save.setGeometry(QtCore.QRect(830, 520, 151, 31))
        self.save.setObjectName("save")
        self.save_file = QtWidgets.QLineEdit(self.centralWidget)
        self.save_file.setGeometry(QtCore.QRect(880, 240, 101, 20))
        self.save_file.setObjectName("save_file")
        self.edit_graph = QtWidgets.QPushButton(self.centralWidget)
        self.edit_graph.setGeometry(QtCore.QRect(830, 460, 151, 31))
        self.edit_graph.setObjectName("edit_graph")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 72, 16))
        self.label_5.setObjectName("label_5")
        self.graph_count = QtWidgets.QLabel(self.centralWidget)
        self.graph_count.setGeometry(QtCore.QRect(90, 0, 51, 16))
        self.graph_count.setObjectName("graph_count")
        self.select_save_loc = QtWidgets.QPushButton(self.centralWidget)
        self.select_save_loc.setGeometry(QtCore.QRect(830, 100, 151, 31))
        self.select_save_loc.setObjectName("select_save_loc")
        self.display_save_loc = QtWidgets.QLineEdit(self.centralWidget)
        self.display_save_loc.setGeometry(QtCore.QRect(830, 140, 151, 20))
        self.display_save_loc.setObjectName("display_save_loc")
        self.save_status = QtWidgets.QLabel(self.centralWidget)
        self.save_status.setGeometry(QtCore.QRect(830, 600, 93, 21))
        self.save_status.setObjectName("save_status")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(890, 560, 35, 21))
        self.label_6.setObjectName("label_6")
        self.program_status = QtWidgets.QLabel(self.centralWidget)
        self.program_status.setGeometry(QtCore.QRect(830, 580, 161, 20))
        self.program_status.setObjectName("program_status")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(10, 0, 804, 41))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setGeometry(QtCore.QRect(814, 19, 3, 611))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setGeometry(QtCore.QRect(10, 620, 804, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_5 = QtWidgets.QFrame(self.centralWidget)
        self.line_5.setGeometry(QtCore.QRect(0, 19, 20, 611))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(880, 270, 101, 181))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioPDF = QtWidgets.QRadioButton(self.groupBox)
        self.radioPDF.setGeometry(QtCore.QRect(10, 0, 82, 20))
        self.radioPDF.setObjectName("radioPDF")
        self.radioPGF = QtWidgets.QRadioButton(self.groupBox)
        self.radioPGF.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.radioPGF.setObjectName("radioPGF")
        self.radioPNG = QtWidgets.QRadioButton(self.groupBox)
        self.radioPNG.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.radioPNG.setObjectName("radioPNG")
        self.radioPS = QtWidgets.QRadioButton(self.groupBox)
        self.radioPS.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.radioPS.setObjectName("radioPS")
        self.radioRGBA = QtWidgets.QRadioButton(self.groupBox)
        self.radioRGBA.setGeometry(QtCore.QRect(10, 80, 82, 17))
        self.radioRGBA.setObjectName("radioRGBA")
        self.radioRAW = QtWidgets.QRadioButton(self.groupBox)
        self.radioRAW.setGeometry(QtCore.QRect(10, 100, 82, 17))
        self.radioRAW.setObjectName("radioRAW")
        self.radioSVGZ = QtWidgets.QRadioButton(self.groupBox)
        self.radioSVGZ.setGeometry(QtCore.QRect(10, 120, 82, 17))
        self.radioSVGZ.setObjectName("radioSVGZ")
        self.radioSVG = QtWidgets.QRadioButton(self.groupBox)
        self.radioSVG.setGeometry(QtCore.QRect(10, 140, 82, 17))
        self.radioSVG.setObjectName("radioSVG")
        self.radioEPS = QtWidgets.QRadioButton(self.groupBox)
        self.radioEPS.setGeometry(QtCore.QRect(10, 160, 82, 17))
        self.radioEPS.setObjectName("radioEPS")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Graph Options"))
        self.Savefile.setText(_translate("MainWindow", "Save File:"))
        self.label_4.setText(_translate("MainWindow", "Format:"))
        self.file_select.setText(_translate("MainWindow", "Select File"))
        self.generate_graphs.setText(_translate("MainWindow", "Generate Graphs"))
        self.file_display.setText(_translate("MainWindow", "No file selected"))
        self.view_previous.setText(_translate("MainWindow", "View Previous"))
        self.view_next.setText(_translate("MainWindow", "View Next"))
        self.save.setText(_translate("MainWindow", "Save"))
        self.edit_graph.setText(_translate("MainWindow", "Edit Graph"))
        self.label_5.setText(_translate("MainWindow", "Viewing Graph:"))
        self.graph_count.setText(_translate("MainWindow", "0/0"))
        self.select_save_loc.setText(_translate("MainWindow", "Select Save Location"))
        self.display_save_loc.setText(_translate("MainWindow", "No location selected"))
        self.save_status.setText(_translate("MainWindow", "No unsaved graphs"))
        self.label_6.setText(_translate("MainWindow", "Status:"))
        self.program_status.setText(_translate("MainWindow", "No Datafiles imported"))
        self.radioPDF.setText(_translate("MainWindow", ".pdf"))
        self.radioPGF.setText(_translate("MainWindow", ".pgf"))
        self.radioPNG.setText(_translate("MainWindow", ".png"))
        self.radioPS.setText(_translate("MainWindow", ".ps"))
        self.radioRGBA.setText(_translate("MainWindow", ".rgba"))
        self.radioRAW.setText(_translate("MainWindow", ".raw"))
        self.radioSVGZ.setText(_translate("MainWindow", ".svgz"))
        self.radioSVG.setText(_translate("MainWindow", ".svg"))
        self.radioEPS.setText(_translate("MainWindow", ".eps"))

